### ISSUE TITLE
Improve uart_iqrf_read()

### ISSUE THREAD

**Issue by fmikulu** [iqrfsdk/clibuart#3]
The function

`int uart_iqrf_read(uint8_t *readBuffer, uint8_t *dataLen, unsigned int timeout)`

shall initialize return value `dataLen` to zero and thus return zero at the very beginning if there is no data ready (timeout).

Lines 404-417 are unnecessary repeated checks. The parameters shall be set by initialization and the only check could be `if (libIsInitialized == 0) { ...`. Allocation can be done in advance by initialization and pointer to allocated buffer kept as a part of T_UART_RECEIVER_CONTROL.

**Comment by spinarr** [comment]
Opraven https://github.com/iqrfsdk/clibuart/commit/e83295c17f6aee8667cc2d25af7d958a4c754748.
